FROM golang:1.22-alpine AS build

WORKDIR /app
COPY go.mod ./
COPY cmd ./cmd
COPY internal ./internal
RUN go build -o /server ./cmd/server

FROM alpine:3.20

WORKDIR /app
COPY --from=build /server /server
EXPOSE 8080
CMD ["/server"]
